export enum ReviewScoringFormula {
  ATTENDANCE_ONLY = 'ATTENDANCE_ONLY',
  PROBLEM_RESOLUTION_CONTRIBUTION = 'PROBLEM_RESOLUTION_CONTRIBUTION',
  ATTENDANCE_PROBLEM_CONTRIBUTION = 'ATTENDANCE_PROBLEM_CONTRIBUTION',
  CUSTOM_SELECTION = 'CUSTOM_SELECTION',
}
